ADIRoadShow/ADIRoadShow/ViewModels/Login/LoginView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ADIRoadShow.ViewModels.Login
{
    public class LoginView
    {
        [Required]
        [Display(Name = "帳號")]
        public string Account { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }
    }
}

ADIRoadShow/ADIRoadShow/Controllers/LoginController.cs
using ADIRoadShow.ActionFilters;
using ADIRoadShow.Models;
using ADIRoadShow.Models.Cmind;
using ADIRoadShow.Repositories;
using ADIRoadShow.Utility.Cmind;
using ADIRoadShow.ViewModels.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ADIRoadShow.Controllers
{
    //[MemberAuthorize]
    [ErrorHandleActionFilter]
    public class LoginController : BaseController
    {
        private ApplyRepository applyRepository = new ApplyRepository();
        private AdminRepository adminRepository = new AdminRepository();
        private ActiveLogRepository activeLogRepository = new ActiveLogRepository();

        // GET: Login
        public ActionResult Index()
        {
            bool isLogin = MemberInfoHelper.IsLogin();
            if (!isLogin) {
                RedirectToAction("Index", "Home");
            }
            var login = new LoginView();
            return View(login);
        }

        /// <summary>
        /// 登入
        /// </summary>
        /// <param name="login"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginView login)
        {
            if (ModelState.IsValid)
            {
                var member = applyRepository.Login(login.Account, login.Password);
                var admin = adminRepository.Login(login.Account, login.Password);
                //var admininfo = AdminInfoHelper.GetAdminInfo();
                if (member != null || admin != null)
                {
                    if (member != null)
                    {
                        MemberInfo memberInfo = new MemberInfo();
                        memberInfo.ID = member.ID;
                        memberInfo.IsAdmin = false;
                        memberInfo.DealerId = (Dealer)member.DealerId;
                        CookieHelper.SetCookie("Dealer", memberInfo.DealerId);
                        MemberInfoHelper.Login(memberInfo, true);
                    }
                    if (admin != null)
                    {
                        MemberInfo memberInfo = new MemberInfo();
                        memberInfo.ID = admin.ID;
                        memberInfo.IsAdmin = true;
                        MemberInfoHelper.Login(memberInfo, true);
                    }
                    ShowMessage(true, "登入成功");
                    var url = CookieHelper.Get("RetrunUrl");
                    if (url != null && (url.IndexOf("Video") != -1 || url.IndexOf("VR") != -1))
                    {
                        return Redirect(url); 
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }

                }
                else
                {
                    ModelState.AddModelError("Password", "帳號或密碼錯誤");
                }
            }
            return View(login);
        }

        public ActionResult Logout(int showRoomType, int exhibitionType = 0)
        {
            var memberInfo = MemberInfoHelper.GetMemberInfo();
            if (!memberInfo.IsAdmin)
            {
                activeLogRepository.UpdateEndTime(memberInfo.ID, showRoomType, exhibitionType);
            }
            MemberInfoHelper.Logout();
            return RedirectToAction("Index","Home");
        }
    }
}

ADIRoadShow/ADIRoadShow/Views/Login/Index.cshtml
@model ADIRoadShow.ViewModels.Login.LoginView
<!-- ****************** PAGE HEADER ******************* -->
<div class="big-title">
    <div class="container container-full">
        <div class="row">
            <div class="col-md-6 text-uppercase">
                <h1>登入</h1>
            </div>
        </div>
    </div>
</div>
<!-- // PAGE HEADER -->
<!-- ****************** PAGE CONTENT ******************* -->
<div class="page-content">
    <div class="container">
        <h1 class="formtittle">沉浸智慧生活 智進未來  2021 ADI 應用科技展</h1>
        <p class="formp">帳號為電子郵件，密碼為行動電話 </p>
        <div class="col-sm-12 col-lg-offset-2 col-lg-8 col-md-12">
            @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { enctype = "multipart/form-data", @class = "contact-form" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="row">
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.Account, new { @placeholder = "帳號", @required = true })
                        @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-12">
                        @Html.TextBoxFor(model => model.Password, new { @placeholder = "密碼", @required = true ,type="password" })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12 signbtn">
                        <button class="btn-flat" type="submit" style="width:177px;margin: 25px 10px;display:inline;font-size:17px">
                            登入
                        </button>
                        <a href="@Url.Action("Index","SignUp")">活動報名</a>
                    </div>
                </div>
                <div class="wpcf7-response-output wpcf7-display-none"></div>
            }
        </div>
    </div>
</div>

@section scripts{
    <script src="//code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script>
        $(window).on('load', function () {
            $("form").each(function () { $.data($(this)[0], 'validator', false); });
            $.validator.unobtrusive.parse("form");
        });

    </script>
}