ADIRoadShow/ADIRoadShow/Areas/Admin/Controllers/ActiveLogAdminController.cs
using ADIRoadShow.ActionFilters;
using ADIRoadShow.Areas.Admin.ViewModels.ActiveLog;
using ADIRoadShow.Models.Cmind;
using ADIRoadShow.Models.JoinModels;
using ADIRoadShow.Repositories;
using ADIRoadShow.Utility.Cmind;
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ADIRoadShow.Areas.Admin.Controllers
{
    public class ActiveLogAdminController : BaseAdminController
    {
        private ActiveLogRepository activeLogRepository = new ActiveLogRepository();

        [Authorize]
        [ErrorHandleAdminActionFilter]
        // GET: Admin/ActiveLogAdmin
        public ActionResult Index(ActiveLogIndexView model)
        {
            var query = activeLogRepository.Query(model.ShowRoomType, model.DealerId, model.ExhibitionType);
            var pageResult = query.ToPageResult<RelActiveLogApply>(model);
            model.PageResult = Mapper.Map<PageResult<ActiveLogView>>(pageResult);
            return View(model);
        }
    }
}

ADIRoadShow/ADIRoadShow/Areas/Admin/Views/ActiveLogAdmin/Index.cshtml
@using ADIRoadShow.Models.Cmind;
@model ADIRoadShow.Areas.Admin.ViewModels.ActiveLog.ActiveLogIndexView
@{
    ViewBag.Title = "Index";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    活動參與紀錄管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "ActiveLogAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.DealerId, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.DealerId, Model.DealerCategoryOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ExhibitionType, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.ExhibitionType, Model.ExhibitionCategoryOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ShowRoomType, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.ShowRoomType, Model.ShowRoomTypeOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">活動參與紀錄列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row table-responsive no-padding">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ApplyId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().DealerId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ShowRoomType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ExhibitionType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Phone)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Email)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Company)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().OnlineTime)
                                            </th>
                                            <th data-sorting="EndTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().EndTime)
                                            </th>
                                            @*<th></th>*@
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ApplyId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().DealerId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ShowRoomType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ExhibitionType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Phone)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Email)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Company)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().OnlineTime)
                                            </th>
                                            <th data-sorting="EndTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().EndTime)
                                            </th>
                                            @*<th></th>*@
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                        <tr>
                                            <td>
                                                @item.ApplyId
                                            </td>
                                            <td>
                                                @item.Name
                                            </td>
                                            <td>
                                                @item.DealerId
                                            </td>
                                            <td>
                                                @(ADIRoadShow.Utility.Cmind.EnumHelper.GetDescription(item.ShowRoomType))
                                            </td>
                                            <td>
                                                @(ADIRoadShow.Utility.Cmind.EnumHelper.GetDescription(item.ExhibitionType))
                                            </td>
                                            <td>
                                                @item.Phone
                                            </td>
                                            <td>
                                                @item.Email
                                            </td>
                                            <td>
                                                @item.Company
                                            </td>
                                            <td>
                                                @item.OnlineTime.ToString("yyyy/MM/dd HH:mm")
                                            </td>
                                            <td>
                                                @(item.EndTime != DateTime.MinValue ? item.EndTime.ToString("yyyy/MM/dd HH:mm") : "無")
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}