ADIRoadShow/ADIRoadShow/ViewModels/Login/LoginView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ADIRoadShow.ViewModels.Login
{
    public class LoginView
    {
        [Required]
        [Display(Name = "帳號")]
        public string Account { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密碼")]
        public string Password { get; set; }
    }
}

ADIRoadShow/ADIRoadShow/Areas/Admin/Controllers/AuthAdminController.cs
using ADIRoadShow.ActionFilters;
using ADIRoadShow.Areas.Admin.ViewModels.Auth;
using ADIRoadShow.Models.Cmind;
using ADIRoadShow.Utility.Cmind;
using ADIRoadShow.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ADIRoadShow.Areas.Admin.Controllers
{
    [ErrorHandleAdminActionFilter]
    public class AuthAdminController : BaseAdminController
    {
        private AdminRepository adminRepository = new AdminRepository();

        // GET: Admin/AuthAdmin
        public ActionResult Login()
        {
#if DEBUG
            if (System.Diagnostics.Debugger.IsAttached)
            {
                var controller = DependencyResolver.Current.GetService<AuthAdminController>();
                controller.ControllerContext = new ControllerContext(this.Request.RequestContext, controller);
                return controller.Login(new LoginView() { Account = "sysadmin", Password = "admin1234" });
            }
#endif
            var login = new LoginView();
            return View(login);
        }

        /// <summary>
        /// 登入
        /// </summary>
        /// <param name="login"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginView login)
        {
            if (ModelState.IsValid)
            {
                var admin = adminRepository.Login(login.Account, login.Password);
                if (admin != null)
                {
                    AdminInfo adminInfo = new AdminInfo();
                    adminInfo.ID = admin.ID;
                    adminInfo.Account = admin.Account;
                    AdminInfoHelper.Login(adminInfo, login.RememberMe);
                    ShowMessage(true, "登入成功");
                    return Redirect(FormsAuthentication.GetRedirectUrl(login.Account, false));

                }
                else
                {
                    ModelState.AddModelError("Password", "帳號或密碼錯誤");
                }
            }

            return View(login);
        }

        [Authorize]
        public ActionResult Logout()
        {
            AdminInfoHelper.Logout();
            return RedirectToAction("Login");
        }
    }
}

ADIRoadShow/ADIRoadShow/Controllers/LoginController.cs
using ADIRoadShow.ActionFilters;
using ADIRoadShow.Models;
using ADIRoadShow.Models.Cmind;
using ADIRoadShow.Repositories;
using ADIRoadShow.Utility.Cmind;
using ADIRoadShow.ViewModels.Login;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ADIRoadShow.Controllers
{
    //[MemberAuthorize]
    [ErrorHandleActionFilter]
    public class LoginController : BaseController
    {
        private ApplyRepository applyRepository = new ApplyRepository();
        private AdminRepository adminRepository = new AdminRepository();
        private ActiveLogRepository activeLogRepository = new ActiveLogRepository();

        // GET: Login
        public ActionResult Index()
        {
            bool isLogin = MemberInfoHelper.IsLogin();
            if (!isLogin) {
                RedirectToAction("Index", "Home");
            }
            var login = new LoginView();
            return View(login);
        }

        /// <summary>
        /// 登入
        /// </summary>
        /// <param name="login"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(LoginView login)
        {
            if (ModelState.IsValid)
            {
                var member = applyRepository.Login(login.Account, login.Password);
                var admin = adminRepository.Login(login.Account, login.Password);
                //var admininfo = AdminInfoHelper.GetAdminInfo();
                if (member != null || admin != null)
                {
                    if (member != null)
                    {
                        MemberInfo memberInfo = new MemberInfo();
                        memberInfo.ID = member.ID;
                        memberInfo.IsAdmin = false;
                        memberInfo.DealerId = (Dealer)member.DealerId;
                        CookieHelper.SetCookie("Dealer", memberInfo.DealerId);
                        MemberInfoHelper.Login(memberInfo, true);
                    }
                    if (admin != null)
                    {
                        MemberInfo memberInfo = new MemberInfo();
                        memberInfo.ID = admin.ID;
                        memberInfo.IsAdmin = true;
                        MemberInfoHelper.Login(memberInfo, true);
                    }
                    ShowMessage(true, "登入成功");
                    var url = CookieHelper.Get("RetrunUrl");
                    if (url != null && (url.IndexOf("Video") != -1 || url.IndexOf("VR") != -1))
                    {
                        return Redirect(url); 
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }

                }
                else
                {
                    ModelState.AddModelError("Password", "帳號或密碼錯誤");
                }
            }
            return View(login);
        }

        public ActionResult Logout(int showRoomType, int exhibitionType = 0)
        {
            var memberInfo = MemberInfoHelper.GetMemberInfo();
            if (!memberInfo.IsAdmin)
            {
                activeLogRepository.UpdateEndTime(memberInfo.ID, showRoomType, exhibitionType);
            }
            MemberInfoHelper.Logout();
            return RedirectToAction("Index","Home");
        }
    }
}

ADIRoadShow/ADIRoadShow/Areas/Admin/Views/AuthAdmin/Login.cshtml
@model ADIRoadShow.Areas.Admin.ViewModels.Auth.LoginView
@{
    var siteNameAbbreviation = @ADIRoadShow.Models.Cmind.SiteSetting.SiteNameAbbreviation;
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin @siteNameAbbreviation  | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/Content/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/AdminLTE-3.0.4/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Content/AdminLTE-3.0.4/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <link href="~/Content/Admin/custom.css" rel="stylesheet" />
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="hold-transition skin-blue login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="#"><b>Admin</b>@siteNameAbbreviation</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-card-body">
            <p class="login-box-msg">Sign in to start your session</p>

            @using (Html.BeginForm("Login", "AuthAdmin", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div class="form-group has-feedback">
                    @Html.TextBoxFor(model => model.Account, new { @class = "form-control", @placeholder = "帳號" })
                    <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    @Html.ValidationMessageFor(model => model.Account, "", new { @class = "text-danger" })
                </div>
                <div class="form-group has-feedback">
                    @Html.TextBoxFor(model => model.Password, new { @type = "password", @class = "form-control", @placeholder = "密碼" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>

                <div class="row">
                    <div class="col-8">
                        <div class="form-check icheck">
                            <label>
                                @Html.CheckBoxFor(model => model.RememberMe, new { @class = "form-check-input" })
                                @Html.DisplayNameFor(model => model.RememberMe)
                            </label>
                        </div>
                    </div>
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">登入</button>
                    </div>
                </div>
            }

        </div>
    </div>

    <!-- jQuery -->
    <script src="~/Content/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/Content/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
</body>
</html>