ADIRoadShow/ADIRoadShow/Areas/Admin/Controllers/MessageAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ADIRoadShow.ActionFilters;
using ADIRoadShow.Areas.Admin.ViewModels.Message;
using ADIRoadShow.Models;
using ADIRoadShow.Models.Cmind;
using ADIRoadShow.Models.JoinModels;
using ADIRoadShow.Repositories;
using ADIRoadShow.Utility.Cmind;
using AutoMapper;

namespace ADIRoadShow.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class MessageAdminController : BaseAdminController
    {
        private MessageRepository messageRepository = new MessageRepository();
        private ApplyRepository applyRepository = new ApplyRepository();

        // GET: Admin/MessageAdmin
        public ActionResult Index(MessageIndexView model)
        {
            var query = messageRepository.Query(model.ShowRoomType, model.IsLock, model.ExhibitionType);
            var pageResult = query.ToPageResult<RelMessageApply>(model);
            model.PageResult = Mapper.Map<PageResult<MessageView>>(pageResult);
            return View(model);
        }

        //public ActionResult Delete(int id)
        //{
        //    messageRepository.Delete(id);
        //    ShowMessage(true, "刪除成功");
        //    return RedirectToAction(nameof(MessageAdminController.Index));
        //}

        public ActionResult Lock(int id)
        {
            applyRepository.IsLock(id);
            ShowMessage(true, "已修改會員狀態");
            return RedirectToAction(nameof(MessageAdminController.Index));
        }
    }
}

ADIRoadShow/ADIRoadShow/Areas/Admin/Views/MessageAdmin/Index.cshtml
@using ADIRoadShow.Models
@model ADIRoadShow.Areas.Admin.ViewModels.Message.MessageIndexView
@{
    ViewBag.Title = "Index";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    留言管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "MessageAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.NickName, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.NickName, new { @class = "form-control", @placeholder = "暱稱" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ShowRoomType, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.ShowRoomType, Model.ShowRoomTypeOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ExhibitionType, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.ExhibitionType, Model.ExhibitionTypeOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.IsLock, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.IsLock, "StatusDropDownList", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">留言列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row table-responsive no-padding">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ShowRoomType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ExhibitionType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().NickName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Content)
                                            </th>

                                            <th data-sorting="CreateTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().CreateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ShowRoomType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().ExhibitionType)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().NickName)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().Content)
                                            </th>
                                            <th data-sorting="CreateTime">
                                                @Html.DisplayNameFor(model => model.PageResult.Data.FirstOrDefault().CreateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                        <tr>
                                            <td>
                                                @(ADIRoadShow.Utility.Cmind.EnumHelper.GetDescription(item.ShowRoomType))
                                            </td>
                                            <td>
                                                @(ADIRoadShow.Utility.Cmind.EnumHelper.GetDescription(item.ExhibitionType))
                                            </td>
                                            <td>
                                                @item.NickName
                                            </td>
                                            <td>
                                                @item.Content
                                            </td>
                                            <td>
                                                @item.CreateTime.ToString("yyyy/MM/dd HH:mm")
                                            </td>
                                            <td>
                                                @if (!item.IsAdmin)
                                                {
                                                    @Html.ActionLink(item.IsLock ? "解除封鎖" : "封鎖", "Lock", new { id = item.ApplyId }, new { @class = "btn btn-primary" })
                                                }
                                                @Html.ActionLink("刪除", "Delete", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>

                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}